version: '3.3'
services:
  app-build:
    image: maven:3.6.0
    volumes:
      - ./api/:/code
    working_dir: /code/
    command: mvn clean install -DskipTests
  app:
    image: openjdk:8-jdk
    volumes:
      - ./api/target/:/code/
    working_dir: /code/
    command: java -jar app-0.0.1-SNAPSHOT.jar
    depends_on:
      - db
    links:
      - db
    ports:
      - '8080:8080'
    environment:
      MYSQL_HOST: 'db'
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'caffeine_db'
      MYSQL_USER: 'caffeine'
      MYSQL_PASSWORD: 'caffeine123'
      MYSQL_ROOT_PASSWORD: 'caffeine123'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
