export const SET_STATE_PROPERTY = 'SET_STATE_PROPERTY'
export const INCREASE_DRINK_QUANTITY = 'INCREASE_DRINK_QUANTITY'
export const DECREASE_DRINK_QUANTITY = 'DECREASE_DRINK_QUANTITY'
export const STATE_RESET = 'STATE_RESET'
